'use strict';
// https://boardgamegeek.com/filepage/43812/polish-translation-card-list
angular
  .module('MyApp')
  .constant("deckConstants", {
    en:{
      basic: [
        {"title":"Gift","group":"item","interrupt":true,"number":1},
        {"title":"Key","group":"item","interrupt":true,"number":2},
        {"title":"Tree","group":"item","interrupt":true,"number":3},
        {"title":"Ring","group":"item","interrupt":false,"number":4},
        {"title":"Door","group":"item","interrupt":false,"number":5},
        {"title":"Window","group":"item","interrupt":false,"number":6},
        {"title":"Spell","group":"item","interrupt":false,"number":7},
        {"title":"Axe","group":"item","interrupt":false,"number":8},
        {"title":"Crown","group":"item","interrupt":false,"number":9},
        {"title":"Boat","group":"item","interrupt":false,"number":10},
        {"title":"Sword","group":"item","interrupt":false,"number":11},
        {"title":"Food","group":"item","interrupt":false,"number":12},
        {"title":"Fire","group":"item","interrupt":false,"number":13},
        {"title":"Book","group":"item","interrupt":false,"number":14},
        {"title":"Treasure","group":"item","interrupt":false,"number":15},
        {"title":"Monster","group":"character","interrupt":true,"number":1},
        {"title":"Horse","group":"character","interrupt":true,"number":2},
        {"title":"Husband/Wife","group":"character","interrupt":true,"number":3},
        {"title":"Orphan","group":"character","interrupt":true,"number":4},
        {"title":"Frog","group":"character","interrupt":true,"number":5},
        {"title":"Princess","group":"character","interrupt":false,"number":6},
        {"title":"Beggar","group":"character","interrupt":false,"number":7},
        {"title":"Brother/Sister","group":"character","interrupt":false,"number":8},
        {"title":"Prince","group":"character","interrupt":false,"number":9},
        {"title":"Queen","group":"character","interrupt":false,"number":10},
        {"title":"King","group":"character","interrupt":false,"number":11},
        {"title":"Giant","group":"character","interrupt":false,"number":12},
        {"title":"Fairy","group":"character","interrupt":false,"number":13},
        {"title":"Stepmother","group":"character","interrupt":false,"number":14},
        {"title":"Old Woman","group":"character","interrupt":false,"number":15},
        {"title":"Parent","group":"character","interrupt":false,"number":16},
        {"title":"Witch","group":"character","interrupt":false,"number":17},
        {"title":"Thief","group":"character","interrupt":false,"number":18},
        {"title":"Bird","group":"character","interrupt":false,"number":19},
        {"title":"Wolf","group":"character","interrupt":false,"number":20},
        {"title":"Cook","group":"character","interrupt":false,"number":21},
        {"title":"Sheperdess","group":"character","interrupt":false,"number":22},
        {"title":"Child","group":"character","interrupt":false,"number":23},
        {"title":"Old Man","group":"character","interrupt":false,"number":24},
        {"title":"Enemy","group":"character","interrupt":false,"number":25},
        {"title":"Contest","group":"event","interrupt":true,"number":1},
        {"title":"Dream","group":"event","interrupt":true,"number":2},
        {"title":"Storm","group":"event","interrupt":true,"number":3},
        {"title":"Plan","group":"event","interrupt":true,"number":4},
        {"title":"Escape","group":"event","interrupt":false,"number":5},
        {"title":"Something is Revealed","group":"event","interrupt":false,"number":6},
        {"title":"A Fight","group":"event","interrupt":false,"number":7},
        {"title":"People Meet","group":"event","interrupt":false,"number":8},
        {"title":"Journey","group":"event","interrupt":false,"number":9},
        {"title":"A Trap","group":"event","interrupt":false,"number":10},
        {"title":"An Argument","group":"event","interrupt":false,"number":11},
        {"title":"Someone Is Hurt","group":"event","interrupt":false,"number":12},
        {"title":"A Chase","group":"event","interrupt":false,"number":13},
        {"title":"Two People Fall In Love","group":"event","interrupt":false,"number":14},
        {"title":"Time Passes","group":"event","interrupt":false,"number":15},
        {"title":"A Death","group":"event","interrupt":false,"number":16},
        {"title":"An Object Breaks","group":"event","interrupt":false,"number":17},
        {"title":"Transformation","group":"event","interrupt":false,"number":18},
        {"title":"People Part Company","group":"event","interrupt":false,"number":19},
        {"title":"A Rescue","group":"event","interrupt":false,"number":20},
        {"title":"Blind","group":"aspect","interrupt":true,"number":1},
        {"title":"This Item Can Talk","group":"aspect","interrupt":true,"number":2},
        {"title":"Evil","group":"aspect","interrupt":true,"number":3},
        {"title":"Stupid","group":"aspect","interrupt":true,"number":4},
        {"title":"Insane","group":"aspect","interrupt":true,"number":5},
        {"title":"Poisoned","group":"aspect","interrupt":false,"number":6},
        {"title":"Sleeping","group":"aspect","interrupt":false,"number":7},
        {"title":"Beautiful","group":"aspect","interrupt":false,"number":8},
        {"title":"Very Strong","group":"aspect","interrupt":false,"number":9},
        {"title":"Hidden","group":"aspect","interrupt":false,"number":10},
        {"title":"Very Wise","group":"aspect","interrupt":false,"number":11},
        {"title":"Secret","group":"aspect","interrupt":false,"number":12},
        {"title":"Frightened","group":"aspect","interrupt":false,"number":13},
        {"title":"Happy","group":"aspect","interrupt":false,"number":14},
        {"title":"Far Away","group":"aspect","interrupt":false,"number":15},
        {"title":"This Animal Can Talk","group":"aspect","interrupt":false,"number":16},
        {"title":"Tiny","group":"aspect","interrupt":false,"number":17},
        {"title":"Long - Lost","group":"aspect","interrupt":false,"number":18},
        {"title":"Ugly","group":"aspect","interrupt":false,"number":19},
        {"title":"Disguised","group":"aspect","interrupt":false,"number":20},
        {"title":"Lucky","group":"aspect","interrupt":false,"number":21},
        {"title":"This Can Fly","group":"aspect","interrupt":false,"number":22},
        {"title":"Cursed","group":"aspect","interrupt":false,"number":23},
        {"title":"Stolen","group":"aspect","interrupt":false,"number":24},
        {"title":"Lost","group":"aspect","interrupt":false,"number":25},
        {"title":"Stairs","group":"places","interrupt":true,"number":1},
        {"title":"Kitchen","group":"places","interrupt":true,"number":2},
        {"title":"Home","group":"places","interrupt":true,"number":3},
        {"title":"Chapel","group":"places","interrupt":true,"number":4},
        {"title":"River","group":"places","interrupt":false,"number":5},
        {"title":"Island","group":"places","interrupt":false,"number":6},
        {"title":"Tower","group":"places","interrupt":false,"number":7},
        {"title":"Cottage","group":"places","interrupt":false,"number":8},
        {"title":"Road","group":"places","interrupt":false,"number":9},
        {"title":"Village","group":"places","interrupt":false,"number":10},
        {"title":"Ruin","group":"places","interrupt":false,"number":11},
        {"title":"Cave","group":"places","interrupt":false,"number":12},
        {"title":"Town","group":"places","interrupt":false,"number":13},
        {"title":"Night","group":"places","interrupt":false,"number":14},
        {"title":"Mountain","group":"places","interrupt":false,"number":15},
        {"title":"Kingdom","group":"places","interrupt":false,"number":16},
        {"title":"At Sea","group":"places","interrupt":false,"number":17},
        {"title":"Prison","group":"places","interrupt":false,"number":18},
        {"title":"Forest","group":"places","interrupt":false,"number":19},
        {"title":"Palace","group":"places","interrupt":false,"number":20},
        {"title":"The King fulfilled his side of the bargain and everyone was happy.","group":"ending","interrupt":false,"number":1},
        {"title":"And he was reunited with his family.","group":"ending","interrupt":false,"number":2},
        {"title":"And so the prophecy had been fulfilled.","group":"ending","interrupt":false,"number":3},
        {"title":"So she revealed her true identity and they were married.","group":"ending","interrupt":false,"number":4},
        {"title":"And there they sit to this very day.","group":"ending","interrupt":false,"number":5},
        {"title":"And to this day no one knows where she ran to.","group":"ending","interrupt":false,"number":6},
        {"title":"So they returned it to its original owner.","group":"ending","interrupt":false,"number":7},
        {"title":"So the queen gave them the prize as she had promised.","group":"ending","interrupt":false,"number":8},
        {"title":"And they were blind for the rest of their days for their wickedness and falsehood.","group":"ending","interrupt":false,"number":9},
        {"title":"So he realized how loyal his brother had been.","group":"ending","interrupt":false,"number":10},
        {"title":"They looked after it until she was old enough.","group":"ending","interrupt":false,"number":11},
        {"title":"And the flames rose higher and the evil place was destroyed.","group":"ending","interrupt":false,"number":12},
        {"title":"He saw the error of his ways and repented.","group":"ending","interrupt":false,"number":13},
        {"title":"So they escaped their captors and fled home","group":"ending","interrupt":false,"number":14},
        {"title":"Which is how the Kingdom got its name.","group":"ending","interrupt":false,"number":15},
        {"title":"Her sorrow came to an end and her joy began.","group":"ending","interrupt":false,"number":16},
        {"title":"As dawn broke they could see it was perfect.","group":"ending","interrupt":false,"number":17},
        {"title":"His dedication had broken the spell.","group":"ending","interrupt":false,"number":18},
        {"title":"And when they died they passed it on to their children.","group":"ending","interrupt":false,"number":19},
        {"title":"Which proves that a pure heart will always triumph in the end.","group":"ending","interrupt":false,"number":20},
        {"title":"So the King agreed to spare his life.","group":"ending","interrupt":false,"number":21},
        {"title":"So it was transformed back into human form.","group":"ending","interrupt":false,"number":22},
        {"title":"They thanked the hero who had saved them all.","group":"ending","interrupt":false,"number":23},
        {"title":"The curse was lifted as had been foretold.","group":"ending","interrupt":false,"number":24},
        {"title":"True love had broken the enchantment.","group":"ending","interrupt":false,"number":25},
        {"title":"And she was reunited with her family.","group":"ending","interrupt":false,"number":26},
        {"title":"So the riddle was finally answered.","group":"ending","interrupt":false,"number":27},
        {"title":"And never as long as she lived could it be removed.","group":"ending","interrupt":false,"number":28},
        {"title":"And the parents were reunited with their long-lost child.","group":"ending","interrupt":false,"number":29},
        {"title":"It fit perfectly.","group":"ending","interrupt":false,"number":30},
        {"title":"And the King was delighted with such an unusual gift.","group":"ending","interrupt":false,"number":31},
        {"title":"You have freed me from my enchantment and tomorrow we will be married.","group":"ending","interrupt":false,"number":32},
        {"title":"With the rival dead they could get married at last.","group":"ending","interrupt":false,"number":33},
        {"title":"But it had vanished as mysteriously as it had appeared.","group":"ending","interrupt":false,"number":34},
        {"title":"And for all I know they could be dancing still.","group":"ending","interrupt":false,"number":35},
        {"title":"But no matter how hard they searched they were never able to find it again.","group":"ending","interrupt":false,"number":36},
        {"title":"Which proves that one should always be more careful of one's companions.","group":"ending","interrupt":false,"number":37},
        {"title":"So they promised never to fight again.","group":"ending","interrupt":false,"number":38},
        {"title":"So the spell was broken and they were free.","group":"ending","interrupt":false,"number":39},
        {"title":"But she still visited them from time to time.","group":"ending","interrupt":false,"number":40},
        {"title":"So the evil-doers were thrown down a well.","group":"ending","interrupt":false,"number":41},
        {"title":"So everything was restored to its former glory.","group":"ending","interrupt":false,"number":42},
        {"title":"She always wore it to help remind her.","group":"ending","interrupt":false,"number":43},
        {"title":"So he told her he was the prince and they lived happily ever after.","group":"ending","interrupt":false,"number":44},
        {"title":"So the village was restored to prosperity.","group":"ending","interrupt":false,"number":45},
        {"title":"So the King relented and the two were married.","group":"ending","interrupt":false,"number":46},
        {"title":"They ate it at the feast and it was delicious.","group":"ending","interrupt":false,"number":47},
        {"title":"She never let it out of her sight again.","group":"ending","interrupt":false,"number":48},
        {"title":"So the rightful ruler was placed once more on the throne.","group":"ending","interrupt":false,"number":49},
        {"title":"He picked up his weapon and went on his way.","group":"ending","interrupt":false,"number":50},
        {"title":"So they changed places and everything was back to normal.","group":"ending","interrupt":false,"number":51},
        {"title":"And he listened to his mother's advice from then on.","group":"ending","interrupt":false,"number":52},
        {"title":"So he forgave her and they were married.","group":"ending","interrupt":false,"number":53},
        {"title":"And the kingdom rejoiced at the end of the tyrant's reign.","group":"ending","interrupt":false,"number":54},
        {"title":"And in the course of time they became King and Queen.","group":"ending","interrupt":false,"number":55}
      ]
    },
    pl:{
      basic: [
        {"title":"Podarunek","group":"item","interrupt":true,"number":1},
        {"title":"Klucz","group":"item","interrupt":true,"number":2},
        {"title":"Drzewo","group":"item","interrupt":true,"number":3},
        {"title":"Pierścień","group":"item","interrupt":false,"number":4},
        {"title":"Drzwi","group":"item","interrupt":false,"number":5},
        {"title":"Okno","group":"item","interrupt":false,"number":6},
        {"title":"Zaklęcie","group":"item","interrupt":false,"number":7},
        {"title":"Topór","group":"item","interrupt":false,"number":8},
        {"title":"Korona","group":"item","interrupt":false,"number":9},
        {"title":"Łódź","group":"item","interrupt":false,"number":10},
        {"title":"Miecz","group":"item","interrupt":false,"number":11},
        {"title":"Jedzenie","group":"item","interrupt":false,"number":12},
        {"title":"Ogień","group":"item","interrupt":false,"number":13},
        {"title":"Księga","group":"item","interrupt":false,"number":14},
        {"title":"Skarb","group":"item","interrupt":false,"number":15},
        {"title":"Potwór","group":"character","interrupt":true,"number":1},
        {"title":"Koń","group":"character","interrupt":true,"number":2},
        {"title":"Mąż / Żona","group":"character","interrupt":true,"number":3},
        {"title":"Sierota","group":"character","interrupt":true,"number":4},
        {"title":"Żaba","group":"character","interrupt":true,"number":5},
        {"title":"Księżniczka","group":"character","interrupt":false,"number":6},
        {"title":"Żebrak","group":"character","interrupt":false,"number":7},
        {"title":"Brat / Siostra","group":"character","interrupt":false,"number":8},
        {"title":"Książę","group":"character","interrupt":false,"number":9},
        {"title":"Królowa","group":"character","interrupt":false,"number":10},
        {"title":"Król","group":"character","interrupt":false,"number":11},
        {"title":"Olbrzym","group":"character","interrupt":false,"number":12},
        {"title":"Wróżka","group":"character","interrupt":false,"number":13},
        {"title":"Macocha","group":"character","interrupt":false,"number":14},
        {"title":"Stara kobieta","group":"character","interrupt":false,"number":15},
        {"title":"Rodzic","group":"character","interrupt":false,"number":16},
        {"title":"Czarownica","group":"character","interrupt":false,"number":17},
        {"title":"Złodziej","group":"character","interrupt":false,"number":18},
        {"title":"Ptak","group":"character","interrupt":false,"number":19},
        {"title":"Wilk","group":"character","interrupt":false,"number":20},
        {"title":"Kucharz","group":"character","interrupt":false,"number":21},
        {"title":"Pasterka","group":"character","interrupt":false,"number":22},
        {"title":"Dziecko","group":"character","interrupt":false,"number":23},
        {"title":"Starzec","group":"character","interrupt":false,"number":24},
        {"title":"Nieprzyjaciel","group":"character","interrupt":false,"number":25},
        {"title":"Zawody / konkurs","group":"event","interrupt":true,"number":1},
        {"title":"Sen / marzenie","group":"event","interrupt":true,"number":2},
        {"title":"Burza / sztorm","group":"event","interrupt":true,"number":3},
        {"title":"Plan","group":"event","interrupt":true,"number":4},
        {"title":"Ucieczka","group":"event","interrupt":false,"number":5},
        {"title":"Ujawnienie tajemnicy","group":"event","interrupt":false,"number":6},
        {"title":"Walka","group":"event","interrupt":false,"number":7},
        {"title":"Spotkanie ludzi","group":"event","interrupt":false,"number":8},
        {"title":"Podróż / wędrówka","group":"event","interrupt":false,"number":9},
        {"title":"Pułapka","group":"event","interrupt":false,"number":10},
        {"title":"Sprzeczka","group":"event","interrupt":false,"number":11},
        {"title":"Ktoś odniósł rany","group":"event","interrupt":false,"number":12},
        {"title":"Pościg","group":"event","interrupt":false,"number":13},
        {"title":"Zakochali się w sobie","group":"event","interrupt":false,"number":14},
        {"title":"Czas mija","group":"event","interrupt":false,"number":15},
        {"title":"Śmierć","group":"event","interrupt":false,"number":16},
        {"title":"Przedmiot został zniszczony","group":"event","interrupt":false,"number":17},
        {"title":"Przemiana","group":"event","interrupt":false,"number":18},
        {"title":"Podział kompanii","group":"event","interrupt":false,"number":19},
        {"title":"Ratunek","group":"event","interrupt":false,"number":20},
        {"title":"Niewidomy","group":"aspect","interrupt":true,"number":1},
        {"title":"Mówiący przedmiot","group":"aspect","interrupt":true,"number":2},
        {"title":"Zło","group":"aspect","interrupt":true,"number":3},
        {"title":"Głupota","group":"aspect","interrupt":true,"number":4},
        {"title":"Obłąkany","group":"aspect","interrupt":true,"number":5},
        {"title":"Zatruty","group":"aspect","interrupt":false,"number":6},
        {"title":"Śpiący","group":"aspect","interrupt":false,"number":7},
        {"title":"Piękny","group":"aspect","interrupt":false,"number":8},
        {"title":"Bardzo silny","group":"aspect","interrupt":false,"number":9},
        {"title":"Ukryty","group":"aspect","interrupt":false,"number":10},
        {"title":"Bardzo mądry","group":"aspect","interrupt":false,"number":11},
        {"title":"Sekretny","group":"aspect","interrupt":false,"number":12},
        {"title":"Przerażony","group":"aspect","interrupt":false,"number":13},
        {"title":"Szczęśliwy","group":"aspect","interrupt":false,"number":14},
        {"title":"Daleko","group":"aspect","interrupt":false,"number":15},
        {"title":"Mówiące zwierzę","group":"aspect","interrupt":false,"number":16},
        {"title":"Malutki","group":"aspect","interrupt":false,"number":17},
        {"title":"Zaginiony dawno temu","group":"aspect","interrupt":false,"number":18},
        {"title":"Brzydki","group":"aspect","interrupt":false,"number":19},
        {"title":"Zamaskowany","group":"aspect","interrupt":false,"number":20},
        {"title":"Szczęściarz","group":"aspect","interrupt":false,"number":21},
        {"title":"Latający","group":"aspect","interrupt":false,"number":22},
        {"title":"Przeklęty","group":"aspect","interrupt":false,"number":23},
        {"title":"Skradziony","group":"aspect","interrupt":false,"number":24},
        {"title":"Zagubiony","group":"aspect","interrupt":false,"number":25},
        {"title":"Schody","group":"places","interrupt":true,"number":1},
        {"title":"Kuchnia","group":"places","interrupt":true,"number":2},
        {"title":"Dom","group":"places","interrupt":true,"number":3},
        {"title":"Kaplica","group":"places","interrupt":true,"number":4},
        {"title":"Rzeka","group":"places","interrupt":false,"number":5},
        {"title":"Wyspa","group":"places","interrupt":false,"number":6},
        {"title":"Wieża","group":"places","interrupt":false,"number":7},
        {"title":"Chatka","group":"places","interrupt":false,"number":8},
        {"title":"Droga","group":"places","interrupt":false,"number":9},
        {"title":"Wioska","group":"places","interrupt":false,"number":10},
        {"title":"Ruiny","group":"places","interrupt":false,"number":11},
        {"title":"Jaskinia","group":"places","interrupt":false,"number":12},
        {"title":"Miasto","group":"places","interrupt":false,"number":13},
        {"title":"Noc","group":"places","interrupt":false,"number":14},
        {"title":"Góry","group":"places","interrupt":false,"number":15},
        {"title":"Królestwo","group":"places","interrupt":false,"number":16},
        {"title":"Na morzu","group":"places","interrupt":false,"number":17},
        {"title":"Więzienie","group":"places","interrupt":false,"number":18},
        {"title":"Las","group":"places","interrupt":false,"number":19},
        {"title":"Pałac","group":"places","interrupt":false,"number":20},
        {"title":"Król dotrzymując umowy, uszczęśliwił wszystkich.","group":"ending","interrupt":false,"number":1},
        {"title":"I odzyskał swoją rodzinę.","group":"ending","interrupt":false,"number":2},
        {"title":"I oto przepowiednia spełniła się.","group":"ending","interrupt":false,"number":3},
        {"title":"Wtedy ujawniła swoją prawdziwą tożsamość i wzięli ślub.","group":"ending","interrupt":false,"number":4},
        {"title":"I siedzą tam aż do dzisiejszego dnia.","group":"ending","interrupt":false,"number":5},
        {"title":"I do dzisiaj nikt się nie dowiedział gdzie uciekła.","group":"ending","interrupt":false,"number":6},
        {"title":"I zwrócili to prawowitemu właścicielowi.","group":"ending","interrupt":false,"number":7},
        {"title":"I królowa nagrodziła ich zgodnie z obietnicą.","group":"ending","interrupt":false,"number":8},
        {"title":"I za swoją niegodziwość i fałszywość stracili wzrok na resztę swoich dni.","group":"ending","interrupt":false,"number":9},
        {"title":"I zdał sobie sprawę jak lojalny był jego brat.","group":"ending","interrupt":false,"number":10},
        {"title":"I strzegli tego dopóki nie podorosła.","group":"ending","interrupt":false,"number":11},
        {"title":"I płomienie objęły złe miejsce niszcząc je doszczętnie.","group":"ending","interrupt":false,"number":12},
        {"title":"I wyraził skruchę gdy zrozumiał swój błąd.","group":"ending","interrupt":false,"number":13},
        {"title":"I wyrwali się porywaczom i uciekli do domu.","group":"ending","interrupt":false,"number":14},
        {"title":"I w ten sposób Królestwo otrzymało swoją nazwę.","group":"ending","interrupt":false,"number":15},
        {"title":"I zakończył się jej smutek ustępując miejsca radości.","group":"ending","interrupt":false,"number":16},
        {"title":"Z nadejściem świtu ujrzeli doskonałość tego.","group":"ending","interrupt":false,"number":17},
        {"title":"I jego poświęcenie zdjęło urok.","group":"ending","interrupt":false,"number":18},
        {"title":"I po śmierci przekazali to swoim dzieciom.","group":"ending","interrupt":false,"number":19},
        {"title":"Co dowodzi, że czyste serce zawsze zwycięża.","group":"ending","interrupt":false,"number":20},
        {"title":"I król darował mu życie.","group":"ending","interrupt":false,"number":21},
        {"title":"I odzyskało ludzką postać.","group":"ending","interrupt":false,"number":22},
        {"title":"I podziękowali bohaterowi za ocalenie.","group":"ending","interrupt":false,"number":23},
        {"title":"I zgodnie z przepowiednią klątwa straciła swą moc.","group":"ending","interrupt":false,"number":24},
        {"title":"Prawdziwa miłość przezwyciężyła urok.","group":"ending","interrupt":false,"number":25},
        {"title":"I odzyskała swoją rodzinę.","group":"ending","interrupt":false,"number":26},
        {"title":"I zagadka została w końcu rozwiązana.","group":"ending","interrupt":false,"number":27},
        {"title":"I nie usunie tego aż do końca życia.","group":"ending","interrupt":false,"number":28},
        {"title":"I rodzice odzyskali swoje dawno zaginione dziecko.","group":"ending","interrupt":false,"number":29},
        {"title":"Pasuje doskonale.","group":"ending","interrupt":false,"number":30},
        {"title":"I król zachwycił się tak niezwykłym darem.","group":"ending","interrupt":false,"number":31},
        {"title":"Uwolniłeś mnie od klątwy, jutro się pobierzemy","group":"ending","interrupt":false,"number":32},
        {"title":"Po śmierci rywala w końcu mogli się pobrać.","group":"ending","interrupt":false,"number":33},
        {"title":"Ale to zniknęło tak samo tajemniczo jak się pojawiło.","group":"ending","interrupt":false,"number":34},
        {"title":"I o ile wiem tańczą do dnia dzisiejszego.","group":"ending","interrupt":false,"number":35},
        {"title":"Ale niezależnie jak bardzo próbowali, nigdy już tego nie odnaleźli.","group":"ending","interrupt":false,"number":36},
        {"title":"Co dowodzi, że zawsze powinno się być ostrożniejszym od reszty kompanów.","group":"ending","interrupt":false,"number":37},
        {"title":"I obiecali nigdy więcej nie walczyć.","group":"ending","interrupt":false,"number":38},
        {"title":"I zaklęcie prysło i stali się wolni.","group":"ending","interrupt":false,"number":39},
        {"title":"Ale od czasu do czasu, wciąż ich odwiedzała.","group":"ending","interrupt":false,"number":40},
        {"title":"I złoczyńcy zostali wrzuceni do studni.","group":"ending","interrupt":false,"number":41},
        {"title":"I wszystko odzyskało swoją dawną wspaniałość.","group":"ending","interrupt":false,"number":42},
        {"title":"I zawsze nosiła to przy sobie, aby nie zapomnieć.","group":"ending","interrupt":false,"number":43},
        {"title":"I powiedział jej, że jest księciem i potem żyli długo i szczęśliwie.","group":"ending","interrupt":false,"number":44},
        {"title":"I wioska powróciła do dawnej świetności.","group":"ending","interrupt":false,"number":45},
        {"title":"I król wyraził zgodę i mogli się pobrać.","group":"ending","interrupt":false,"number":46},
        {"title":"I zjedli to podczas uczty a było wyśmienite.","group":"ending","interrupt":false,"number":47},
        {"title":"I nigdy więcej nie spuściła tego z oczu.","group":"ending","interrupt":false,"number":48},
        {"title":"I prawowity władca powrócił na tron.","group":"ending","interrupt":false,"number":49},
        {"title":"I podniósł broń i poszedł w swoją stronę.","group":"ending","interrupt":false,"number":50},
        {"title":"I zamienili się miejscami i wszystko powróciło do normalności.","group":"ending","interrupt":false,"number":51},
        {"title":"I od tego czasu słuchał matczynych rad.","group":"ending","interrupt":false,"number":52},
        {"title":"I przebaczył jej i się pobrali.","group":"ending","interrupt":false,"number":53},
        {"title":"I całe królestwo cieszyło się z końca rządów tyrana.","group":"ending","interrupt":false,"number":54},
        {"title":"I z czasem zostali królem i królową.","group":"ending","interrupt":false,"number":55}
      ]
    }
  }
)
